---
title: "Assignment 7 - MSCA 31007"
author: "Melanie Tran"
date: "11/9/2020"
output: html_document
---

Setup.
```{r setup, include=FALSE}
dataPath <- setwd('/Users/meltra02/Desktop/MSCA/Quarter 1/31007 - Stats Analysis/Session 7 - 31007')

test_dat <- read.table(paste(dataPath,'Week7_Test_Sample.csv',sep = '/'), header=TRUE)

head(test_dat$Output) # output Y values;
head(test_dat$Input1) # first predictor value
head(test_dat$Input2)# second predictor values

head(cbind(Output = test_dat$Output, Input1 = test_dat$Input1, Input2 = test_dat$Input2))


nOutput <- length(test_dat$Output)
```


Fit the model.
```{r}
fit.1<-lm(Output~1,data=test_dat) #no inputs
fit.1.2<-lm(Output~1+Input1,data=test_dat) #only Input1
fit.1.3<-lm(Output~1+Input2,data=test_dat) #only Input 2
fit.1.2.3<-lm(Output~.,data=test_dat) #Input 1 & Input 2

```

1) Sum of Squares explained by Input 1 in model fit.1.2
```{r}
anova(fit.1.2)$"Sum Sq"

SSM<-sum((fit.1.2$fitted.values-mean(test_dat$Output))^2) 
SSM #sum of squares explained

#y_bar <- mean(test_dat$Output)
#SST <- sum((test_dat$Output - y_bar)**2)
#SST
anova(fit.1.2)$"Sum Sq"[1]
cat("Question 1 is", round(SSM,3))

```

2) Sum of Squares unexplained by Input 1 in model fit.1.2

```{r}
SSE<-sum(fit.1.2$residuals^2)
SSE
anova(fit.1.2)$"Sum Sq"[2]
cat("Question 2 is", round(SSE,3))
```

3) Sum of Squares explained by Input2 in model fit.1.3

```{r}
anova(fit.1.3)
SSM<-sum((fit.1.3$fitted.values-mean(test_dat$Output))^2) 
SSM #sum of squares explained

#y_bar <- mean(test_dat$Output)
#SST <- sum((test_dat$Output - y_bar)**2)
#SST
anova(fit.1.3)$"Sum Sq"[1]
cat("Question 3 is", round(SSM,3))



```

4) Sum of Squares unexplained by Input 2 in model fit.1.3

```{r}
SSE<-sum(fit.1.3$residuals^2)
SSE
anova(fit.1.3)$"Sum Sq"[2]
cat("Question 4 is", round(SSE,3))
```
5) F statistic for comparison of fit.1 and fit.1.2.3

```{r}
f_stat <- anova(fit.1,fit.1.2.3)$F[2]
f_stat


c(anova(fit.1,fit.1.2.3)$F[2],summary(fit.1.2.3)$fstatistic[1])
cat("Question 5 is ", round(f_stat,3))
```

6) P-value for comparison of fit.1 with fit.1.2.3:
```{r}
summary(fit.1.2.3)$fstatistic

round(anova(fit.1,fit.1.2.3)$"Pr(>F)",3)


```
7) Which inputs should be removed?

```{r}
print("second")
```

